version: '3.4'

services:
  sector.services.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44364;http://+:59647
      - ASPNETCORE_HTTPS_PORT=44364
    ports:
      - "59647:59647"
      - "44364:44364"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  sector.rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  sector.mongo:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port