version: '3.6'

services:
  sector.services.identity:
    image: sector.services.identity:${TAG:-latest}
    build:
      context: .
      dockerfile: ../src/1.Services/Identity/Sector.Services.Identity/Dockerfile

  sector.rabbitmq:
    image: rabbitmq:3-management

  sector.mongodb:
    image: mongo:${TAG:-latest}